apiVersion: apps/v1
kind: Deployment
metadata:
  name: devjeans-server
  namespace: devjeans
  labels:
    app: devjeans
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devjeans
      tier: backend
  template:
    metadata:
      labels:
        app: devjeans
        tier: backend
      annotations:
        kops.k8s.io/instancegroup: nodes
    spec:
      nodeSelector:
        kops.k8s.io/instancegroup: nodes
      containers:
      - name: devjeans-server
        image: patnmat/devjeans-server:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "1024Mi" # 1GiB
            cpu: "500m" # 0.5 vCPU
          limits:
            memory: "2048Mi"
            cpu: "1000m"
        envFrom:
        - configMapRef:
            name: server-config
        # - secretRef:
        #     name: server-secrets
        volumeMounts:
        - name: devjeans-server
          mountPath: "/devjeans/server/logs" # 로그 디렉토리 경로
      volumes:
      - name: devjeans-server
        emptyDir: {} # 파드가 삭제될 때 볼륨도 같이 삭제됨. 영구보존 원할 시 pvc 생성할 것
---
apiVersion: v1
kind: Service
metadata:
  name: devjeans-server-service
  namespace: devjeans
  labels:
    app: devjeans
spec:
  type: ClusterIP
  selector:
    app: devjeans
    tier: backend
  ports:
  - name: http
    port: 8080
    targetPort: 8080
