apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: server-ing
spec:
  ingressClassName: nginx
  rules:
    - host: api-test.dev-hee.com ## Route53에 수동으로 ingress nlb와 연결 필요 
      http:
        paths:
          - backend:
              service:
                name: server-svc  
                port:
                  number: 8080
            path: /
            pathType: Prefix
