apiVersion: apps/v1
kind: Deployment
metadata:
  name: devjeans-server
  labels:
    app: devjeans
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devjeans
      tier: backend
  template:
    metadata:
      labels:
        app: devjeans
        tier: backend
    spec:
      containers:
        - name: devjeans-server
          image: patnmat/devjeans-server:latest
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: server-config
            - secretRef:
                name: server-secrets
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: server-ing
spec:
  ingressClassName: nginx
  rules:
    - host: api-test.dev-hee.com
      http:
        paths:
          - backend:
              service:
                name: api-svc  
                port:
                  number: 8080
            path: /
            pathType: Prefix
