apiVersion: apps/v1
kind: Deployment
metadata:
  name: devjeans-front
  labels:
    tier: front
    app: devjeans
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devjeans
      tier: front
  template:
    metadata:
      labels:
        app: devjeans
        tier: front
    spec:
      containers:
        - name: devjeans-front
          image: patnmat/devjeans-front:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: devjeans-front
  labels:
    app: devjeans
    tier: front
spec:
  selector:
    app: devjeans
    tier: front
  ports:
    - name: front
      port: 80
      targetPort: 80

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fornt-ing
spec:
  ingressClassName: nginx
  rules:
    - host: stg-devjeans.dev-hee.com
      http:
        paths:
          - backend:
              service:
                name: devjeans-front
                port:
                  number: 80
            path: /
            pathType: Prefix
